name: Deploy Telegram Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.BOT_KEY }}
          log-public-key: false

      - name: Deploy to VPS
        run: |
          # Prepare directory
          echo "Creating directory..."
          ssh -o StrictHostKeyChecking=no -o LogLevel=QUIET -o UserKnownHostsFile=/dev/null atom@${{ secrets.SERVER_IP }} "mkdir -p /home/atom/goBot" > /dev/null 2>&1
          
          # Upload code
          echo "Uploading code..."
          rsync -q --no-verbose -e "ssh -o StrictHostKeyChecking=no -o LogLevel=QUIET -o UserKnownHostsFile=/dev/null" ./ atom@${{ secrets.SERVER_IP }}:/home/atom/goBot/ --exclude .git > /dev/null 2>&1
          
          # Create env file
          echo "Creating env file..."
          ssh -o StrictHostKeyChecking=no -o LogLevel=QUIET -o UserKnownHostsFile=/dev/null atom@${{ secrets.SERVER_IP }} "cat > /home/atom/goBot/.env << 'EOL'
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          SCHEDULE_TIME=0 9 * * *
          NEWS_CATEGORY=technology
          NEWS_LANGUAGE=en
          EOL" > /dev/null 2>&1
          
          # Deploy
          echo "Starting deployment..."
          ssh -o StrictHostKeyChecking=no -o LogLevel=QUIET -o UserKnownHostsFile=/dev/null atom@${{ secrets.SERVER_IP }} "
            cd /home/atom/goBot &&
            TIMESTAMP=\$(date +%s) &&
            IMAGE=\"gobot:\$TIMESTAMP\" &&
            docker build --pull --no-cache -t \$IMAGE . &&
            docker run -d --name gobot_new --restart unless-stopped --network host --env-file .env \$IMAGE &&
            sleep 15 &&
            docker ps -a | grep -q gobot_prod && docker stop gobot_prod && docker rm gobot_prod || true &&
            docker rename gobot_new gobot_prod &&
            docker images 'gobot:*' --format '{{.ID}}' | tail -n +4 | xargs -r docker rmi
          "
          echo "Deployment completed successfully"
